### ISSUE TITLE
SECOND Baseline Results Table 5

### ISSUE THREAD

**Issue by gfkri** [yinjunbo/ProficientTeachers#2]
Hi,
thank you for your work.

I was just wondering, how you trained the SECOND baseline in Table 5 of you paper. For example, your 50% of the data should be 25% of the entire training set, which is already more than the 20% where the OpenPCDet implementation achieves 62.58 AP LEVEL2 on Vehicles [1]. Obviously the GT sampling needs to be adjusted there. Do you filter your GT database accordingly or do you disable it entirely? And did you adjust anything else compared to OpenPCDet?
Thank you very much advance.

Best regards,
Georg

[1] https://github.com/open-mmlab/OpenPCDet#waymo-open-dataset-baselines

**Comment by yinjunbo** [comment]
Hi Georg,

Thanks for you attention on our work.
The key difference between our SECOND implementation and OpenPCDet lies in
the data downsampling strategy.
OpenPCDet downsamples the waymo training set in a *frame-level, *while our
work downsamples it with a *scene-level(or sequence-level) *following the
ONCE setting*.*
As introduced in the Sec. 4.1, 399 sequences  are used for training, and
thus 50% data means ~200 sequences (each sequence has ~200 frames). The
gt-database is also generated merely from these 200 sequences (we donot
disable it).
Sampling by frame usually shows better performance than sampling
by sequence due to the better diversity, so it's normal that our
performance is lower than OpenPCDet.

Best,
Junbo


Georg Krispel ***@***.***> 于2022年10月17日周一 17:34写道：

**Comment by gfkri** [comment]
Hi Junbo,

thank you very much for your quick answer. Ah, I see, that makes sense. Do you do it the same with ProposalContrast? (because, there it states that the training data is "uniformly sampled") Thank you very much in advance.

Best,
Georg

**Comment by yinjunbo** [comment]
Hi Georg,

This is not the same with ProposalContrast.
ProposalContrast applies *frame-level *donwsampling strategy for we find
the diversiy of downsteam data is important in fine-tuning. So we
downsample frames from the sequences uniformly in ProposalContrast, and
gt-database is obtained in terms of these frames.
Hope this helps.

Best,
Junbo

Georg Krispel ***@***.***> 于2022年10月17日周一 19:42写道：

**Comment by gfkri** [comment]
Thank you.
Best,
Georg
